spring:
  profiles:
    default: local

---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
      platform: mysql # 이거 없으면 mysql 인식 못함

  jwt: # CLI 명령어 - openssl rand -base64 32 로 생성된 값
    secret: VZvl0mIgwU2UmDMXqa7CL79kdBUYz+IvHQWmNsWT4uA=

  datasource:
    url: jdbc:mysql://localhost:3306/MarketBridge
    username: objects
    password: 1234

  #  datasource:
#    url: jdbc:h2:tcp://localhost/~/Marketbridge
#    username: sa
#    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data-mysql.sql 실행
    # 이게 없으면 data-mysql.sql 스크립트가 수행 안 되고 에러 발생합니당.

  h2:
    console:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.sql: debug




payment:
  toss:
    test_client_api_key : "test_ck_GePWvyJnrK2PmxlyQWMqVgLzN97E"
    test_secret_api_key : "test_sk_QbgMGZzorzyG7E6ZkybPVl5E1em4:"
    success_url : "http://localhost:8080/payments/toss/success"
    fail_url : "http://localhost:8080/payments/toss/fail"
---

spring:
  config:
    activate:
      on-profile: test

  sql:
    init:
      mode: always

  jwt: # CLI 명령어 - openssl rand -base64 32 로 생성된 값
    secret: VZvl0mIgwU2UmDMXqa7CL79kdBUYz+IvHQWmNsWT4uA=

  datasource:
#    url: jdbc:mysql://localhost:3306/MarketBridge
#    username: objects
#    password: 1234
#    url: jdbc:h2:tcp://localhost/~/Marketbridge
    url: jdbc:h2:mem:~/Marketbridge
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100



  h2:
    console:
      enabled: true


logging:
  level:
    org.hibernate.sql: debug

payment:
  toss:
    test_client_api_key: "test_ck_GePWvyJnrK2PmxlyQWMqVgLzN97E"
    test_secret_api_key: "test_sk_QbgMGZzorzyG7E6ZkybPVl5E1em4:"
    success_url: "http://localhost:8080/payments/toss/success"
    fail_url: "http://localhost:8080/payments/toss/fail"
